create table if not exists public.llm_usage_ledger (
  id bigint generated by default as identity primary key,
  usage_id text not null unique,
  recorded_at timestamptz not null default now(),
  operation text not null
    check (operation in ('event_extraction', 'event_resolution', 'vision_eval', 'editor_agent', 'other')),
  provider text not null,
  model text not null,
  status text not null
    check (status in ('succeeded', 'failed')),
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  total_tokens integer not null default 0,
  cached_input_tokens integer not null default 0,
  reasoning_output_tokens integer not null default 0,
  cost_micro_cny bigint not null default 0,
  latency_ms integer,
  source_run_id text,
  collector_job_id text,
  article_snapshot_id text,
  event_draft_id text,
  excluded_article_id text,
  metadata jsonb not null default '{}'::jsonb,
  constraint llm_usage_ledger_tokens_nonnegative check (
    input_tokens >= 0
    and output_tokens >= 0
    and total_tokens >= 0
    and cached_input_tokens >= 0
    and reasoning_output_tokens >= 0
    and (latency_ms is null or latency_ms >= 0)
  ),
  constraint llm_usage_ledger_cost_nonnegative check (cost_micro_cny >= 0)
);

create index if not exists llm_usage_ledger_recorded_at_idx
  on public.llm_usage_ledger (recorded_at desc);

create index if not exists llm_usage_ledger_model_idx
  on public.llm_usage_ledger (provider, model, recorded_at desc);

create index if not exists llm_usage_ledger_operation_idx
  on public.llm_usage_ledger (operation, recorded_at desc);

create index if not exists llm_usage_ledger_source_run_idx
  on public.llm_usage_ledger (source_run_id, recorded_at desc)
  where source_run_id is not null;

create index if not exists llm_usage_ledger_failure_idx
  on public.llm_usage_ledger (recorded_at desc)
  where status = 'failed';

create or replace function public.llm_usage_ledger_no_update()
returns trigger
language plpgsql
as $$
begin
  raise exception 'llm_usage_ledger is append-only';
end;
$$;

drop trigger if exists llm_usage_ledger_no_update on public.llm_usage_ledger;
create trigger llm_usage_ledger_no_update
  before update on public.llm_usage_ledger
  for each row execute function public.llm_usage_ledger_no_update();

create or replace function public.llm_usage_ledger_no_delete()
returns trigger
language plpgsql
as $$
begin
  raise exception 'llm_usage_ledger is append-only';
end;
$$;

drop trigger if exists llm_usage_ledger_no_delete on public.llm_usage_ledger;
create trigger llm_usage_ledger_no_delete
  before delete on public.llm_usage_ledger
  for each row execute function public.llm_usage_ledger_no_delete();
